// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv2R5IQqz-txcCKgXd_SBBn3PU4ChNjpc',
    appId: '1:24833729323:web:ae91d86056aac248159b6e',
    messagingSenderId: '24833729323',
    projectId: 'zymo-app',
    authDomain: 'zymo-app.firebaseapp.com',
    storageBucket: 'zymo-app.firebasestorage.app',
    measurementId: 'G-CXDR6GCXCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoMpMbFXbCWFHglRfOs8rBU54sUBect3Y',
    appId: '1:24833729323:android:74359d252037cc0c159b6e',
    messagingSenderId: '24833729323',
    projectId: 'zymo-app',
    storageBucket: 'zymo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZuyfe3sgK8pB2Dz_sAcPun00T4n1bGo',
    appId: '1:24833729323:ios:bb82e3f94dfc50bf159b6e',
    messagingSenderId: '24833729323',
    projectId: 'zymo-app',
    storageBucket: 'zymo-app.firebasestorage.app',
    iosBundleId: 'com.example.zymoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHZuyfe3sgK8pB2Dz_sAcPun00T4n1bGo',
    appId: '1:24833729323:ios:bb82e3f94dfc50bf159b6e',
    messagingSenderId: '24833729323',
    projectId: 'zymo-app',
    storageBucket: 'zymo-app.firebasestorage.app',
    iosBundleId: 'com.example.zymoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv2R5IQqz-txcCKgXd_SBBn3PU4ChNjpc',
    appId: '1:24833729323:web:a41e25ff14765e6e159b6e',
    messagingSenderId: '24833729323',
    projectId: 'zymo-app',
    authDomain: 'zymo-app.firebaseapp.com',
    storageBucket: 'zymo-app.firebasestorage.app',
    measurementId: 'G-04N46N6XXY',
  );
}
